version: '3'

services:
  localws:
    container_name: localws
    hostname: localws
    image: nginx:1.21.6
    ports:
      - 1234:80
    volumes:
      - ./logs:/var/log/nginx
      - ./res:/usr/share/nginx/html
