version: '3'

services:
  front-gate:
    build: ./front-gate
    ports:
      - 1234:1234
    volumes:
      - ./logs/webapp:/usr/local/openresty/nginx/logs
      - ./front-gate/nginx:/etc/nginx/conf.d
      - ./front-gate/luas/signit.lua:/usr/local/openresty/nginx/signit.lua
      - ./app/build:/usr/share/nginx/html
    networks:
      - keys

  gate-keeper:
    image: openresty/openresty
    ports:
      - 1235:1234
    env_file:
      - ./gate-keeper/.env
    volumes:
      - ./logs/gate-keeper:/usr/local/openresty/nginx/logs
      - ./gate-keeper/openresty/bakeKeys.conf:/etc/nginx/conf.d/bakeKeys.conf
      - ./gate-keeper/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gate-keeper/luas/setup.lua:/usr/local/openresty/nginx/setup.lua
      - ./gate-keeper/luas/bake-key.lua:/usr/local/openresty/nginx/bake-key.lua
    networks:
      - keys

volumes:
  redis-cache:

networks:
  keys:
